spring.application.name=InternalManagementSystem

# Use the Environment Variables from Render, or fallback to local for VS Code
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/internalManagementSystem}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

# Hibernate Settings
spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# CRITICAL FIX: Changed from 'create' to 'update' 
# 'create' deletes your database every time the app starts. 
# 'update' keeps your data safe.
spring.jpa.hibernate.ddl-auto=update

# Port for Render
server.port=${PORT:8080}
spring.jpa.open-in-view=false